# # Lustra's migration system
#
# Migrations in Lustra are very similar to Active Record migrations.
# Migrations are two-way modifications of the database.
#
# They help keep a consistent database state during your application's
# development lifecycle.
#
# There are two ways to create a migration:
#
# ## Lustra command
#
# ### TL;DR
#
# You can create a new file in `src/db/migrate` using:
#
# `lustra-cli migration:g migration_name`
#
# This creates a migration in `src/db/migration/[:uid]_migration_name.cr`
# with a UID number and a `MigrationName` class.
#
# ### Advanced options
#
# You can use `lustra-cli migration help` to get advanced options.
#
# ## Manually
#
# You can create a class following this naming convention:
# `Anything + Number.`
# The number is then used to order migrations and must be unique.
#
# Following the rule that inclusion is often better than inheritance, just
# include the module `Lustra::Migration` to your class.
#
# ## Methods of migration
#
# ### Migration direction
#
# Only one method must be overridden: `change`. Compared with ActiveRecord,
# there are no `up` and `down` methods. Instead, you can put specific up/down
# code like this:
#
# ```
# def change(dir)
#   dir.down { irreversible! }
# end
# ```
#
# ```
# def change(dir)
#   add_column :users, :full_name, :string
#
#   dir.up do
#     execute("UPDATE users SET full_name = (SELECT first_name || ' '  || last_name) from users")
#   end
# end
# ```
module Lustra::Migration
  Log = ::Log.for("lustra.migration")

  include Lustra::ErrorMessages

  abstract def uid : Int64

  # This error is raised when you try to revert an irreversible migration.
  class IrreversibleMigration < Exception; end

  module Helper
    TYPE_MAPPING = {
      "string" => "text",
      "int32"  => "int",

      "int64"      => "bigint",
      "long"       => "bigint",
      "bigdecimal" => "numeric",

      "datetime" => "timestamp without time zone",
    }

    # Replace some common types with their PostgreSQL equivalents.
    # If the type is not found in the correspondence table, return it unchanged.
    def self.datatype(type : String)
      ts = type
      TYPE_MAPPING[type]? || ts
    end

    def irreversible!
      raise IrreversibleMigration.new(migration_irreversible(self.class.name))
    end

    def execute(sql : String)
      @operations << Lustra::Migration::Execute.new(sql)
    end

    def add_operation(op : Operation)
      op.migration = self
      @operations << op
    end

    abstract def change(dir)

    # This will apply the migration in a given direction (up or down)
    def apply(dir : Direction = Lustra::Migration::Direction::Up)
      Lustra::Migration::Manager.instance.ensure_ready

      Lustra::SQL.transaction do
        Log.info { "[#{dir}] #{self.class.name}" }

        # If the migration is called twice (e.g. in specs), ensure operations are
        # cleaned up before trying again.
        @operations.clear

        change(dir)

        dir.up do
          @operations.each do |op|
            op.up.each { |x| Lustra::SQL.execute(x.as(String)) }
          end

          SQL.insert("__lustra_metadatas", {metatype: "migration", value: uid.to_s}).execute
        end

        dir.down do
          @operations.reverse_each do |op|
            op.down.each { |x| Lustra::SQL.execute(x.as(String)) }
          end

          SQL.delete("__lustra_metadatas").where({metatype: "migration", value: uid.to_s}).execute
        end

        self
      end
    end
  end

  include Helper

  macro included
    @operations : Array(Operation) = [] of Operation

    # Return the migration number (Unique ID or UID) for migration sorting.
    #
    # Default behavior, by priority:
    #
    # - The UID is generated by the class name if it ends with a number.
    # - If there are no numbers in the migration class, it tries to use the id in the filename.
    # - If not found, an exception is raised. Concrete migrations can override this method.
    #
    # Example:
    #
    # `class MyMigration1234567 # << Order = 1234567`
    # `file db/1234567_my_migration.cr # << Order = 1234567`
    def uid : Int64
      Int64.new(begin
        filename = File.basename(__FILE__)

        if self.class.name =~ /[0-9]+$/
          self.class.name[/[0-9]+$/]
        elsif filename =~ /^[0-9]+/
          filename[/^[0-9]+/]
        else
          raise uid_not_found(self.class.name)
        end
      end)
    end
  end

  macro included
    Lustra::Migration::Manager.instance.add(new)
  end
end

# :nodoc:
# This class is here to prevent bug #5705
# and will be removed when the bug is fixed.
class DummyMigration
  include Lustra::Migration

  def uid : Int64
    -0x01_i64
  end

  def change(dir)
    # Nothing
  end
end

require "./operation"
